import React from "react";
import DemoHeader from "./DemoHeader";

const Demo = ({ onButtonClick }) => {
  return (
    <>
      <DemoHeader />
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
      <div>Demo</div>
    </>
  );
};

export default Demo;
